"""
NameError
Es una excepción que se produce cuando se intenta utilizar un nombre o una variable que no está definido en el contexto actual. 
Esto ocurre cuando se hace referencia a un nombre que no existe o que no ha sido asignado previamente.
"""

## Ejemplo 1
#print(variable_inexistente) # Genera un NameError: name 'variable_inexistente' is not defined
# Descomenta y ejecuta para ver el error

## Ejemplo 2
#def mi_funcion():
    #print(mensaje)  # Genera un NameError: name 'mensaje' is not defined

#mi_funcion()
# Descomenta y ejecuta para ver el error
